#!/usr/bin/python
__author__ = 'joel'


from gi.repository import Gtk, Gdk, GdkPixbuf
from gi.repository.GdkPixbuf import Pixbuf


DRAG_ACTION = Gdk.DragAction.COPY

TARGET_ENTRY_TEXT = 0
COLUMN_TEXT = 0

DRAG_ACTION = Gdk.DragAction.COPY

class DragDropWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Drag and Drop Demo")
        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        self.add(vbox)
        hbox = Gtk.Box()
        vbox.pack_start(hbox, True, True, 0)
        self.iconview = DragSourceIconView()
        self.drop_area = DropArea()
        hbox.pack_start(self.iconview, True, True, 0)
        hbox.pack_start(self.drop_area, True, True, 0)
        self.add_text_targets()

    def add_text_targets(self, button=None):
        self.drop_area.drag_dest_set_target_list(None)
        self.iconview.drag_source_set_target_list(None)
        self.drop_area.drag_dest_add_text_targets()
        self.iconview.drag_source_add_text_targets()

class DragSourceIconView(Gtk.IconView):
    def __init__(self):
        Gtk.IconView.__init__(self)
        self.set_text_column(COLUMN_TEXT)
        model = Gtk.ListStore(str)
        self.set_model(model)
        self.add_item("Item 1")
        self.add_item("Item 2")
        self.add_item("Item 3")
        self.enable_model_drag_source(Gdk.ModifierType.BUTTON1_MASK, [],
            DRAG_ACTION)
        self.connect("drag-data-get", self.on_drag_data_get)

    def on_drag_data_get(self, widget, drag_context, data, info, time):
        selected_path = self.get_selected_items()[0]
        selected_iter = self.get_model().get_iter(selected_path)
        if info == TARGET_ENTRY_TEXT:
            text = self.get_model().get_value(selected_iter, COLUMN_TEXT)
            data.set_text(text, -1)

    def add_item(self, text):
        self.get_model().append([text])


class ButtonDragging(Gtk.CellRendererText):
    def __init__(self):
        Gtk.CellRendererText.__init__(self)
#        self.set_text_column(COLUMN_TEXT)
#        model = Gtk.ListStore(str)
#        self.set_model(model)
#        self.add_item("~")
        self.enable_model_drag_source(Gdk.ModifierType.BUTTON1_MASK, [], DRAG_ACTION)
        self.connect("drag-data-get", self.on_drag_data_get)

    def on_drag_data_get(self, widget, drag_context, data, info, time):
        selected_path = self.get_selected_items()[0]
        selected_iter = self.get_model().get_iter(selected_path)
        text = self.get_model().get_value(selected_iter, COLUMN_TEXT)
        data.set_text(text, -1)

    def add_item(self, text):
        self.get_model().append([text])



class ButtonDrop(Gtk.Label):
    def __init__(self):
        Gtk.Label.__init__(self, "")
        self.drag_dest_set(Gtk.DestDefaults.ALL, [], DRAG_ACTION)
        self.connect("drag-data-received", self.on_drag_data_received)

    def on_drag_data_received(self, widget, drag_context, x,y, data,info, time):
        text = data.get_text()
        print("Received text: %s" % text)


class TableWindow(Gtk.Window):
    def text_edited(self, widget, path, text):
        self.liststore[path][1] = text

    def make_key(self, tl="",tr="",bl="",br=""):
        self.liststore = Gtk.ListStore(str, str)
        self.liststore.append([tl,tr])
        self.liststore.append([bl,br])
        treeview = Gtk.TreeView(model=self.liststore)
        col1_cr = Gtk.CellRendererText()
        col1 = Gtk.TreeViewColumn("l", col1_cr, text=0)
        treeview.append_column(col1)
        re = Gtk.CellRendererText()
        re.set_property("editable", True)
        col2_cr = Gtk.CellRendererText()
        col2_cr.set_property("editable", True)
 #       col2_cr.set_property("alignment", Gtk.CellRendererText.pango.alignment.LEFT)
        col2 = Gtk.TreeViewColumn("r", col2_cr, text=1)
        treeview.append_column(col2)
        col2_cr.connect("edited", self.text_edited)
        treeview.set_headers_visible(False)
        return treeview

    def __init__(self):
        Gtk.Window.__init__(self, title="Table Example")
        fullgrid = Gtk.Grid(column_homogeneous=True, row_homogeneous=True, column_spacing=10, row_spacing=10)
        self.add(fullgrid)
#        tlde = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
#        tl = ButtonDragging()


        tlde = self.make_key(tl="~", tr="~")

        tlde = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button()
        tr = Gtk.Button()
        bl = Gtk.Button()
        br = Gtk.Button()
        tlde.attach(tl, 0, 0, 1, 1)
        tlde.attach(tr, 1, 0, 1, 1)
        tlde.attach(bl, 0, 1, 1, 1)
        tlde.attach(br, 1, 1, 1, 1)



#        ae01 = self.make_key(tl="!", bl="1")


        ae01 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="!")
        tr = Gtk.Button()
        bl = Gtk.Button(label="1")
        br = Gtk.Button()
        ae01.attach(tl, 0, 0, 1, 1)
        ae01.attach(tr, 1, 0, 1, 1)
        ae01.attach(bl, 0, 1, 1, 1)
        ae01.attach(br, 1, 1, 1, 1)

        

        ae02 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="@")
        tr = Gtk.Button()
        bl = Gtk.Button(label="2")
        br = Gtk.Button()
        ae02.attach(tl, 0, 0, 1, 1)
        ae02.attach(tr, 1, 0, 1, 1)
        ae02.attach(bl, 0, 1, 1, 1)
        ae02.attach(br, 1, 1, 1, 1)


        ae03 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="#")
        tr = Gtk.Button()
        bl = Gtk.Button(label="3")
        br = Gtk.Button()
        ae03.attach(tl, 0, 0, 1, 1)
        ae03.attach(tr, 1, 0, 1, 1)
        ae03.attach(bl, 0, 1, 1, 1)
        ae03.attach(br, 1, 1, 1, 1)

        ae04 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="$")
        tr = Gtk.Button()
        bl = Gtk.Button(label="4")
        br = Gtk.Button()
        ae04.attach(tl, 0, 0, 1, 1)
        ae04.attach(tr, 1, 0, 1, 1)
        ae04.attach(bl, 0, 1, 1, 1)
        ae04.attach(br, 1, 1, 1, 1)

        ae05 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="%")
        tr = Gtk.Button()
        bl = Gtk.Button(label="5")
        br = Gtk.Button()
        ae05.attach(tl, 0, 0, 1, 1)
        ae05.attach(tr, 1, 0, 1, 1)
        ae05.attach(bl, 0, 1, 1, 1)
        ae05.attach(br, 1, 1, 1, 1)

        ae06 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="^")
        tr = Gtk.Button()
        bl = Gtk.Button(label="6")
        br = Gtk.Button()
        ae06.attach(tl, 0, 0, 1, 1)
        ae06.attach(tr, 1, 0, 1, 1)
        ae06.attach(bl, 0, 1, 1, 1)
        ae06.attach(br, 1, 1, 1, 1)

        ae07 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="&")
        tr = Gtk.Button()
        bl = Gtk.Button(label="7")
        br = Gtk.Button()
        ae07.attach(tl, 0, 0, 1, 1)
        ae07.attach(tr, 1, 0, 1, 1)
        ae07.attach(bl, 0, 1, 1, 1)
        ae07.attach(br, 1, 1, 1, 1)

        ae08 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="*")
        tr = Gtk.Button()
        bl = Gtk.Button(label="8")
        br = Gtk.Button()
        ae08.attach(tl, 0, 0, 1, 1)
        ae08.attach(tr, 1, 0, 1, 1)
        ae08.attach(bl, 0, 1, 1, 1)
        ae08.attach(br, 1, 1, 1, 1)

        ae09 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="(")
        tr = Gtk.Button()
        bl = Gtk.Button(label="9")
        br = Gtk.Button()
        ae09.attach(tl, 0, 0, 1, 1)
        ae09.attach(tr, 1, 0, 1, 1)
        ae09.attach(bl, 0, 1, 1, 1)
        ae09.attach(br, 1, 1, 1, 1)

        ae10 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label=")")
        tr = Gtk.Button()
        bl = Gtk.Button(label="0")
        br = Gtk.Button()
        ae10.attach(tl, 0, 0, 1, 1)
        ae10.attach(tr, 1, 0, 1, 1)
        ae10.attach(bl, 0, 1, 1, 1)
        ae10.attach(br, 1, 1, 1, 1)

        ae11 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="{")
        tr = Gtk.Button()
        bl = Gtk.Button(label="[")
        br = Gtk.Button()
        ae11.attach(tl, 0, 0, 1, 1)
        ae11.attach(tr, 1, 0, 1, 1)
        ae11.attach(bl, 0, 1, 1, 1)
        ae11.attach(br, 1, 1, 1, 1)

        ae12 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="}")
        tr = Gtk.Button()
        bl = Gtk.Button(label="]")
        br = Gtk.Button()
        ae12.attach(tl, 0, 0, 1, 1)
        ae12.attach(tr, 1, 0, 1, 1)
        ae12.attach(bl, 0, 1, 1, 1)
        ae12.attach(br, 1, 1, 1, 1)

        bksp = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="backsp")
        tr = Gtk.Button()
        bl = Gtk.Button(label="backsp")
        br = Gtk.Button()
        bksp.attach(tl, 0, 0, 1, 1)
        bksp.attach(tr, 1, 0, 1, 1)
        bksp.attach(bl, 0, 1, 1, 1)
        bksp.attach(br, 1, 1, 1, 1)



        tab = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="tab")
        tr = Gtk.Button()
        bl = Gtk.Button(label="tab")
        br = Gtk.Button()
        tab.attach(tl, 0, 0, 1, 1)
        tab.attach(tr, 1, 0, 1, 1)
        tab.attach(bl, 0, 1, 1, 1)
        tab.attach(br, 1, 1, 1, 1)


        ad01 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="\"")
        tr = Gtk.Button()
        bl = Gtk.Button(label="'")
        br = Gtk.Button()
        ad01.attach(tl, 0, 0, 1, 1)
        ad01.attach(tr, 1, 0, 1, 1)
        ad01.attach(bl, 0, 1, 1, 1)
        ad01.attach(br, 1, 1, 1, 1)

        ad02 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="<")
        tr = Gtk.Button()
        bl = Gtk.Button(label=",")
        br = Gtk.Button()
        ad02.attach(tl, 0, 0, 1, 1)
        ad02.attach(tr, 1, 0, 1, 1)
        ad02.attach(bl, 0, 1, 1, 1)
        ad02.attach(br, 1, 1, 1, 1)

        ad03 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label=">")
        tr = Gtk.Button()
        bl = Gtk.Button(label=".")
        br = Gtk.Button()
        ad03.attach(tl, 0, 0, 1, 1)
        ad03.attach(tr, 1, 0, 1, 1)
        ad03.attach(bl, 0, 1, 1, 1)
        ad03.attach(br, 1, 1, 1, 1)


        ad04 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="P")
        tr = Gtk.Button()
        bl = Gtk.Button(label="p")
        br = Gtk.Button()
        ad04.attach(tl, 0, 0, 1, 1)
        ad04.attach(tr, 1, 0, 1, 1)
        ad04.attach(bl, 0, 1, 1, 1)
        ad04.attach(br, 1, 1, 1, 1)


        ad05 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="Y")
        tr = Gtk.Button()
        bl = Gtk.Button(label="y")
        br = Gtk.Button()
        ad05.attach(tl, 0, 0, 1, 1)
        ad05.attach(tr, 1, 0, 1, 1)
        ad05.attach(bl, 0, 1, 1, 1)
        ad05.attach(br, 1, 1, 1, 1)


        ad06 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="F")
        tr = Gtk.Button()
        bl = Gtk.Button(label="f")
        br = Gtk.Button()
        ad06.attach(tl, 0, 0, 1, 1)
        ad06.attach(tr, 1, 0, 1, 1)
        ad06.attach(bl, 0, 1, 1, 1)
        ad06.attach(br, 1, 1, 1, 1)

        ad07 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="G")
        tr = Gtk.Button()
        bl = Gtk.Button(label="g")
        br = Gtk.Button()
        ad07.attach(tl, 0, 0, 1, 1)
        ad07.attach(tr, 1, 0, 1, 1)
        ad07.attach(bl, 0, 1, 1, 1)
        ad07.attach(br, 1, 1, 1, 1)

        ad08 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="C")
        tr = Gtk.Button()
        bl = Gtk.Button(label="c")
        br = Gtk.Button()
        ad08.attach(tl, 0, 0, 1, 1)
        ad08.attach(tr, 1, 0, 1, 1)
        ad08.attach(bl, 0, 1, 1, 1)
        ad08.attach(br, 1, 1, 1, 1)


        ad09 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="R")
        tr = Gtk.Button()
        bl = Gtk.Button(label="r")
        br = Gtk.Button()
        ad09.attach(tl, 0, 0, 1, 1)
        ad09.attach(tr, 1, 0, 1, 1)
        ad09.attach(bl, 0, 1, 1, 1)
        ad09.attach(br, 1, 1, 1, 1)

        ad10 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="L")
        tr = Gtk.Button()
        bl = Gtk.Button(label="l")
        br = Gtk.Button()
        ad10.attach(tl, 0, 0, 1, 1)
        ad10.attach(tr, 1, 0, 1, 1)
        ad10.attach(bl, 0, 1, 1, 1)
        ad10.attach(br, 1, 1, 1, 1)

        ad11 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="?")
        tr = Gtk.Button()
        bl = Gtk.Button(label="/")
        br = Gtk.Button()
        ad11.attach(tl, 0, 0, 1, 1)
        ad11.attach(tr, 1, 0, 1, 1)
        ad11.attach(bl, 0, 1, 1, 1)
        ad11.attach(br, 1, 1, 1, 1)


        ad12 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="+")
        tr = Gtk.Button()
        bl = Gtk.Button(label="=")
        br = Gtk.Button()
        ad12.attach(tl, 0, 0, 1, 1)
        ad12.attach(tr, 1, 0, 1, 1)
        ad12.attach(bl, 0, 1, 1, 1)
        ad12.attach(br, 1, 1, 1, 1)

        bksl = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="|")
        tr = Gtk.Button()
        bl = Gtk.Button(label="\\")
        br = Gtk.Button()
        bksl.attach(tl, 0, 0, 1, 1)
        bksl.attach(tr, 1, 0, 1, 1)
        bksl.attach(bl, 0, 1, 1, 1)
        bksl.attach(br, 1, 1, 1, 1)









        caps = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="caps")
        tr = Gtk.Button()
        bl = Gtk.Button(label="caps")
        br = Gtk.Button()
        caps.attach(tl, 0, 0, 1, 1)
        caps.attach(tr, 1, 0, 1, 1)
        caps.attach(bl, 0, 1, 1, 1)
        caps.attach(br, 1, 1, 1, 1)

        ac01 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="A")
        tr = Gtk.Button()
        bl = Gtk.Button(label="a")
        br = Gtk.Button()
        ac01.attach(tl, 0, 0, 1, 1)
        ac01.attach(tr, 1, 0, 1, 1)
        ac01.attach(bl, 0, 1, 1, 1)
        ac01.attach(br, 1, 1, 1, 1)

        ac02 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="O")
        tr = Gtk.Button()
        bl = Gtk.Button(label="o")
        br = Gtk.Button()
        ac02.attach(tl, 0, 0, 1, 1)
        ac02.attach(tr, 1, 0, 1, 1)
        ac02.attach(bl, 0, 1, 1, 1)
        ac02.attach(br, 1, 1, 1, 1)


        ac03 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="E")
        tr = Gtk.Button()
        bl = Gtk.Button(label="e")
        br = Gtk.Button()
        ac03.attach(tl, 0, 0, 1, 1)
        ac03.attach(tr, 1, 0, 1, 1)
        ac03.attach(bl, 0, 1, 1, 1)
        ac03.attach(br, 1, 1, 1, 1)

        ac04 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="U")
        tr = Gtk.Button()
        bl = Gtk.Button(label="u")
        br = Gtk.Button()
        ac04.attach(tl, 0, 0, 1, 1)
        ac04.attach(tr, 1, 0, 1, 1)
        ac04.attach(bl, 0, 1, 1, 1)
        ac04.attach(br, 1, 1, 1, 1)

        ac05 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="I")
        tr = Gtk.Button()
        bl = Gtk.Button(label="i")
        br = Gtk.Button()
        ac05.attach(tl, 0, 0, 1, 1)
        ac05.attach(tr, 1, 0, 1, 1)
        ac05.attach(bl, 0, 1, 1, 1)
        ac05.attach(br, 1, 1, 1, 1)

        ac06 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="D")
        tr = Gtk.Button()
        bl = Gtk.Button(label="d")
        br = Gtk.Button()
        ac06.attach(tl, 0, 0, 1, 1)
        ac06.attach(tr, 1, 0, 1, 1)
        ac06.attach(bl, 0, 1, 1, 1)
        ac06.attach(br, 1, 1, 1, 1)

        ac07 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="H")
        tr = Gtk.Button()
        bl = Gtk.Button(label="h")
        br = Gtk.Button()
        ac07.attach(tl, 0, 0, 1, 1)
        ac07.attach(tr, 1, 0, 1, 1)
        ac07.attach(bl, 0, 1, 1, 1)
        ac07.attach(br, 1, 1, 1, 1)

        ac08 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="T")
        tr = Gtk.Button()
        bl = Gtk.Button(label="t")
        br = Gtk.Button()
        ac08.attach(tl, 0, 0, 1, 1)
        ac08.attach(tr, 1, 0, 1, 1)
        ac08.attach(bl, 0, 1, 1, 1)
        ac08.attach(br, 1, 1, 1, 1)

        ac09 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="N")
        tr = Gtk.Button()
        bl = Gtk.Button(label="n")
        br = Gtk.Button()
        ac09.attach(tl, 0, 0, 1, 1)
        ac09.attach(tr, 1, 0, 1, 1)
        ac09.attach(bl, 0, 1, 1, 1)
        ac09.attach(br, 1, 1, 1, 1)

        ac10 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="S")
        tr = Gtk.Button()
        bl = Gtk.Button(label="s")
        br = Gtk.Button()
        ac10.attach(tl, 0, 0, 1, 1)
        ac10.attach(tr, 1, 0, 1, 1)
        ac10.attach(bl, 0, 1, 1, 1)
        ac10.attach(br, 1, 1, 1, 1)

        ac11 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="_")
        tr = Gtk.Button()
        bl = Gtk.Button(label="-")
        br = Gtk.Button()
        ac11.attach(tl, 0, 0, 1, 1)
        ac11.attach(tr, 1, 0, 1, 1)
        ac11.attach(bl, 0, 1, 1, 1)
        ac11.attach(br, 1, 1, 1, 1)

        rtrn = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="rtrn")
        tr = Gtk.Button()
        bl = Gtk.Button(label="rtrn")
        br = Gtk.Button()
        rtrn.attach(tl, 0, 0, 1, 1)
        rtrn.attach(tr, 1, 0, 1, 1)
        rtrn.attach(bl, 0, 1, 1, 1)
        rtrn.attach(br, 1, 1, 1, 1)





        lfsh = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="lfsh")
        tr = Gtk.Button()
        bl = Gtk.Button(label="lfsh")
        br = Gtk.Button()
        lfsh.attach(tl, 0, 0, 1, 1)
        lfsh.attach(tr, 1, 0, 1, 1)
        lfsh.attach(bl, 0, 1, 1, 1)
        lfsh.attach(br, 1, 1, 1, 1)

        ab01 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label=":")
        tr = Gtk.Button()
        bl = Gtk.Button(label=";")
        br = Gtk.Button()
        ab01.attach(tl, 0, 0, 1, 1)
        ab01.attach(tr, 1, 0, 1, 1)
        ab01.attach(bl, 0, 1, 1, 1)
        ab01.attach(br, 1, 1, 1, 1)

        ab02 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="Q")
        tr = Gtk.Button()
        bl = Gtk.Button(label="q")
        br = Gtk.Button()
        ab02.attach(tl, 0, 0, 1, 1)
        ab02.attach(tr, 1, 0, 1, 1)
        ab02.attach(bl, 0, 1, 1, 1)
        ab02.attach(br, 1, 1, 1, 1)

        ab03 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="J")
        tr = Gtk.Button()
        bl = Gtk.Button(label="j")
        br = Gtk.Button()
        ab03.attach(tl, 0, 0, 1, 1)
        ab03.attach(tr, 1, 0, 1, 1)
        ab03.attach(bl, 0, 1, 1, 1)
        ab03.attach(br, 1, 1, 1, 1)

        ab04 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="K")
        tr = Gtk.Button()
        bl = Gtk.Button(label="k")
        br = Gtk.Button()
        ab04.attach(tl, 0, 0, 1, 1)
        ab04.attach(tr, 1, 0, 1, 1)
        ab04.attach(bl, 0, 1, 1, 1)
        ab04.attach(br, 1, 1, 1, 1)

        ab05 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="X")
        tr = Gtk.Button()
        bl = Gtk.Button(label="x")
        br = Gtk.Button()
        ab05.attach(tl, 0, 0, 1, 1)
        ab05.attach(tr, 1, 0, 1, 1)
        ab05.attach(bl, 0, 1, 1, 1)
        ab05.attach(br, 1, 1, 1, 1)


        ab06 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="B")
        tr = Gtk.Button()
        bl = Gtk.Button(label="b")
        br = Gtk.Button()
        ab06.attach(tl, 0, 0, 1, 1)
        ab06.attach(tr, 1, 0, 1, 1)
        ab06.attach(bl, 0, 1, 1, 1)
        ab06.attach(br, 1, 1, 1, 1)

        ab07 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="M")
        tr = Gtk.Button()
        bl = Gtk.Button(label="m")
        br = Gtk.Button()
        ab07.attach(tl, 0, 0, 1, 1)
        ab07.attach(tr, 1, 0, 1, 1)
        ab07.attach(bl, 0, 1, 1, 1)
        ab07.attach(br, 1, 1, 1, 1)

        ab08 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="W")
        tr = Gtk.Button()
        bl = Gtk.Button(label="w")
        br = Gtk.Button()
        ab08.attach(tl, 0, 0, 1, 1)
        ab08.attach(tr, 1, 0, 1, 1)
        ab08.attach(bl, 0, 1, 1, 1)
        ab08.attach(br, 1, 1, 1, 1)


        ab09 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="V")
        tr = Gtk.Button()
        bl = Gtk.Button(label="v")
        br = Gtk.Button()
        ab09.attach(tl, 0, 0, 1, 1)
        ab09.attach(tr, 1, 0, 1, 1)
        ab09.attach(bl, 0, 1, 1, 1)
        ab09.attach(br, 1, 1, 1, 1)


        ab10 = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="Z")
        tr = Gtk.Button()
        bl = Gtk.Button(label="z")
        br = Gtk.Button()
        ab10.attach(tl, 0, 0, 1, 1)
        ab10.attach(tr, 1, 0, 1, 1)
        ab10.attach(bl, 0, 1, 1, 1)
        ab10.attach(br, 1, 1, 1, 1)


        rtsh = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="ls")
        tr = Gtk.Button()
        bl = Gtk.Button(label="ls")
        br = Gtk.Button()
        rtsh.attach(tl, 0, 0, 1, 1)
        rtsh.attach(tr, 1, 0, 1, 1)
        rtsh.attach(bl, 0, 1, 1, 1)
        rtsh.attach(br, 1, 1, 1, 1)


        lctl = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="lc")
        tr = Gtk.Button()
        bl = Gtk.Button(label="lc")
        br = Gtk.Button()
        lctl.attach(tl, 0, 0, 1, 1)
        lctl.attach(tr, 1, 0, 1, 1)
        lctl.attach(bl, 0, 1, 1, 1)
        lctl.attach(br, 1, 1, 1, 1)


        lwin = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="lw")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        lwin.attach(tl, 0, 0, 1, 1)
        lwin.attach(tr, 1, 0, 1, 1)
        lwin.attach(bl, 0, 1, 1, 1)
        lwin.attach(br, 1, 1, 1, 1)

        lalt = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="la")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        lalt.attach(tl, 0, 0, 1, 1)
        lalt.attach(tr, 1, 0, 1, 1)
        lalt.attach(bl, 0, 1, 1, 1)
        lalt.attach(br, 1, 1, 1, 1)

        spce = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="spce")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        spce.attach(tl, 0, 0, 1, 1)
        spce.attach(tr, 1, 0, 1, 1)
        spce.attach(bl, 0, 1, 1, 1)
        spce.attach(br, 1, 1, 1, 1)

        ralt = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="ra")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        ralt.attach(tl, 0, 0, 1, 1)
        ralt.attach(tr, 1, 0, 1, 1)
        ralt.attach(bl, 0, 1, 1, 1)
        ralt.attach(br, 1, 1, 1, 1)

        rwin = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="rw")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        rwin.attach(tl, 0, 0, 1, 1)
        rwin.attach(tr, 1, 0, 1, 1)
        rwin.attach(bl, 0, 1, 1, 1)
        rwin.attach(br, 1, 1, 1, 1)

        menu = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="me")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()
        menu.attach(tl, 0, 0, 1, 1)
        menu.attach(tr, 1, 0, 1, 1)
        menu.attach(bl, 0, 1, 1, 1)
        menu.attach(br, 1, 1, 1, 1)

        rctl = Gtk.Grid(column_homogeneous=True, row_homogeneous=True)
        tl = Gtk.Button(label="rc")
        tr = Gtk.Button()
        bl = Gtk.Button(label="")
        br = Gtk.Button()

        rctl.attach(tl, 0, 0, 1, 1)
        rctl.attach(tr, 1, 0, 1, 1)
        rctl.attach(bl, 0, 1, 1, 1)
        rctl.attach(br, 1, 1, 1, 1)

        fullgrid.attach(tlde,  0, 0, 4, 4)
        fullgrid.attach(ae01,  4, 0, 4, 4)

        fullgrid.attach(ae02,  8, 0, 4, 4)
        fullgrid.attach(ae03, 12, 0, 4, 4)
        fullgrid.attach(ae04, 16, 0, 4, 4)
        fullgrid.attach(ae05, 20, 0, 4, 4)
        fullgrid.attach(ae06, 24, 0, 4, 4)
        fullgrid.attach(ae07, 28, 0, 4, 4)
        fullgrid.attach(ae08, 32, 0, 4, 4)
        fullgrid.attach(ae09, 36, 0, 4, 4)
        fullgrid.attach(ae10, 40, 0, 4, 4)
        fullgrid.attach(ae11, 44, 0, 4, 4)
        fullgrid.attach(ae12, 48, 0, 4, 4)
        fullgrid.attach(bksp, 52, 0, 8, 4)

        fullgrid.attach(tab,   0, 4, 6, 4)
        fullgrid.attach(ad01,  6, 4, 4, 4)
        fullgrid.attach(ad02, 10, 4, 4, 4)
        fullgrid.attach(ad03, 14, 4, 4, 4)
        fullgrid.attach(ad04, 18, 4, 4, 4)
        fullgrid.attach(ad05, 22, 4, 4, 4)
        fullgrid.attach(ad06, 26, 4, 4, 4)
        fullgrid.attach(ad07, 30, 4, 4, 4)
        fullgrid.attach(ad08, 34, 4, 4, 4)
        fullgrid.attach(ad09, 38, 4, 4, 4)
        fullgrid.attach(ad10, 42, 4, 4, 4)
        fullgrid.attach(ad11, 46, 4, 4, 4)
        fullgrid.attach(ad12, 50, 4, 4, 4)
        fullgrid.attach(bksl, 54, 4, 6, 4)

        fullgrid.attach(caps,  0, 8, 7, 4)
        fullgrid.attach(ac01,  7, 8, 4, 4)
        fullgrid.attach(ac02, 11, 8, 4, 4)
        fullgrid.attach(ac03, 15, 8, 4, 4)
        fullgrid.attach(ac04, 19, 8, 4, 4)
        fullgrid.attach(ac05, 23, 8, 4, 4)
        fullgrid.attach(ac06, 27, 8, 4, 4)
        fullgrid.attach(ac07, 31, 8, 4, 4)
        fullgrid.attach(ac08, 35, 8, 4, 4)
        fullgrid.attach(ac09, 39, 8, 4, 4)
        fullgrid.attach(ac10, 43, 8, 4, 4)
        fullgrid.attach(ac11, 47, 8, 4, 4)
        fullgrid.attach(rtrn, 51, 8, 9, 4)


        fullgrid.attach(lfsh,  0, 12, 9, 4)
        fullgrid.attach(ab01,  9, 12, 4, 4)
        fullgrid.attach(ab02, 13, 12, 4, 4)
        fullgrid.attach(ab03, 17, 12, 4, 4)
        fullgrid.attach(ab04, 21, 12, 4, 4)
        fullgrid.attach(ab05, 25, 12, 4, 4)
        fullgrid.attach(ab06, 29, 12, 4, 4)
        fullgrid.attach(ab07, 33, 12, 4, 4)
        fullgrid.attach(ab08, 37, 12, 4, 4)
        fullgrid.attach(ab09, 41, 12, 4, 4)
        fullgrid.attach(ab10, 45, 12, 4, 4)
        fullgrid.attach(rtsh, 49, 12, 11,4)

        fullgrid.attach(lctl, 0, 16, 5, 4)
        fullgrid.attach(lwin, 5, 16, 5, 4)
        fullgrid.attach(lalt, 10, 16, 5, 4)
        fullgrid.attach(spce, 15, 16, 25, 4)
        fullgrid.attach(ralt, 40, 16, 5, 4)
        fullgrid.attach(rwin, 45, 16, 5, 4)
        fullgrid.attach(menu, 50, 16, 5, 4)
        fullgrid.attach(rctl, 55, 16, 5, 4)
"""
        self.liststore = Gtk.ListStore(str, str)
        self.liststore.append(["a", "b"])
        self.liststore.append(["c", "d"])

        self.treeview = Gtk.TreeView(model=self.liststore)

        renderer_text = Gtk.CellRendererText()
        column_text = Gtk.TreeViewColumn("t", renderer_text, text=0)
        self.treeview.append_column(column_text)

        renderer_editabletext = Gtk.CellRendererText()
        renderer_editabletext.set_property("editable", True)

        column_editabletext = Gtk.TreeViewColumn("Editable Text",
            renderer_editabletext, text=1)
        self.treeview.append_column(column_editabletext)

        renderer_editabletext.connect("edited", self.text_edited)
        self.treeview.set_headers_visible(False)
"""



win = TableWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
